language: node_js
node_js:
  - "9"
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAUWTGZJ4AECYSUNP4
  secret_access_key:
    secure: DI1MzK+5m7ZI+9m+oGWf5iomNuRyUnO+mb0F+sGtSDv7OyIXFAg2VQC4dmaQBUy2kXr/ygTFXSIjj6gm4qtGzn2WzQmF3FIpnCDuO+yEQfU/dhmZYTN0kKbalV4B7JDnqFKAC8VI+MMZJ+QfuIFbGJUmdI5SvrDq+IXeoRHiUr/tq6dyhpmh6R8gxxb5NSu6oo1ta/Ow/s45SW5IETeH9rEHcCFX/i6+nXJxoog6VZgwvyDhpAPjuJj20F4CufgjcTPombHtR5t8AMJGyzsNRuS27JRcVGr1CKfSusJlFhRMu42deMHTT46/Otxlurw2QCSdXeBuD70m/tZe8KUrdMKL2686a9o/sGdvmWTuQuVfnfCU4snACcdTeu65dyMsDpshimmKVjIZWW3VzKVvHgyaysTkfXkF/0mO2ob44uGG0LSdWPjQMfV97WJJeWQtzppkDkkpFCMy+iWLH6SA6O692GlS/msusEPWSuZSq8nlcVZIOUpoZk+UKhYj+nfpNAJCme/X64yJkkIYJXu0islVayqN0PXuiBUSPBGhFdeoIOyF5mPXeZ9qbQqlVuPutbYjY88mOwn7DH7Yao18MI+7T8WjlF28TnLHg/WtSQeG/EscvYBLbOr1GolqByYHSO6ZBsozfzFVif7WsORDG63iC9pwyH2oK/HAFyK7dzM=
  bucket: zappcast.com
  local-dir: public
  acl: public_read
  skip_cleanup: true
  region: ap-southeast-2 
  on:
    repo: etopiei/zappcast
